# Streamlit Cloud Secrets Configuration
# DO NOT commit this file with real API keys to GitHub
# This is a template - add your real keys in Streamlit Cloud dashboard

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"

# Google Ads Configuration  
GOOGLE_ADS_API_KEY = "your_google_ads_api_key_here"
GOOGLE_ADS_CUSTOMER_ID = "your_customer_id_here"
GOOGLE_ADS_DEVELOPER_TOKEN = "your_developer_token_here"

# Facebook/Meta Configuration
FACEBOOK_API_KEY = "your_facebook_api_key_here"
FACEBOOK_APP_ID = "your_app_id_here"
FACEBOOK_APP_SECRET = "your_app_secret_here"

# LinkedIn Configuration
LINKEDIN_API_KEY = "your_linkedin_api_key_here"
LINKEDIN_CLIENT_ID = "your_client_id_here"
LINKEDIN_CLIENT_SECRET = "your_client_secret_here"

# Database Configuration (if needed)
DATABASE_URL = "your_database_url_here"

# Other API Keys
TWITTER_API_KEY = "your_twitter_api_key_here"
TWITTER_API_SECRET = "your_twitter_api_secret_here"

